### ISSUE TITLE
Install conflicts with pre-existing content, specifically collections and folder display view

### ISSUE THREAD

**Issue by 3dogMcNeill** [collective/Products.FacultyStaffDirectory#4]
Tested on fresh install of Plone 5.0.4. with FSD 5.0

If installing FSD on a clean instance, as in directly from buildout, it seems to work without issues. 

However, there are issues if there is pre-existing content on the clean instance. Specifically, FSD seems to have a conflict with collections and options for folder display views. It may be a compatability issue of collections in FSD with those in Plone 5...

To replicate:
1. Install clean 5.0.4 instance.
2. Create a folder and add two objects. Tag those objects with the same tag.
3. Create a collection with that tag.
4. Replace the Home/"Welcome" page with the collection.
5. Add FSD to buildout and then install in site setup. 
6. You will get an error when trying to access the home page, which was set to be a collection. 
7. When you navigate to the folder you created with the two objects in it, and click on "Display" from the editing bar, the options have changed (see image below)

![test folder site](https://cloud.githubusercontent.com/assets/7101218/18686906/b8d216ce-7f4b-11e6-8c8b-e88640510f9f.png)

**Comment by tkimnguyen** [comment]
@gil-cano thanks for that fix! I never would have figured it out. :) But why is your commit not showing up here in master? ...ah I see it's in the testing branch. Do you want to make a pull request?

**Comment by tkimnguyen** [comment]
@gil-cano I just cherry picked that commit into master

**Comment by gil-cano** [comment]
@tkimnguyen this issue was making some test fail. We still have to fix 1 failure and 2 test to make a pull requets. Thanks for taking this to master.

**Comment by tkimnguyen** [comment]
@gil-cano thanks for your fix! Yeah I saw that and was trying to figure out how to resolve the conflict. Will try again today.
